version: '3.7'
services:
  t_app2:
    container_name: t_app2
    restart: always
    image: golang:1.20
    working_dir: /app
    command: /app/up.sh
    stdin_open: true
    tty: true
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
    env_file:
      - .env
    stop_grace_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.02'
          memory: 128M
#       delay: 5s
#       max_attempts: 5
#       window: 120s

